worker_processes 1;

error_log /Users/chenmeng/code/react-redux-realworld-example-app/logs/nginx-error.log;
pid /Users/chenmeng/code/react-redux-realworld-example-app/nginx-temp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /opt/homebrew/etc/nginx/mime.types;
  default_type application/octet-stream;

  access_log /Users/chenmeng/code/react-redux-realworld-example-app/logs/nginx-access.log;

  sendfile on;
  keepalive_timeout 65;

  client_body_temp_path /Users/chenmeng/code/react-redux-realworld-example-app/nginx-temp/client_body_temp;
  proxy_temp_path /Users/chenmeng/code/react-redux-realworld-example-app/nginx-temp/proxy_temp;
  fastcgi_temp_path /Users/chenmeng/code/react-redux-realworld-example-app/nginx-temp/fastcgi_temp;
  uwsgi_temp_path /Users/chenmeng/code/react-redux-realworld-example-app/nginx-temp/uwsgi_temp;
  scgi_temp_path /Users/chenmeng/code/react-redux-realworld-example-app/nginx-temp/scgi_temp;

  server {
    listen 8088;
    server_name localhost;

    root /Users/chenmeng/code/react-redux-realworld-example-app/build;
    index index.html;

    location /api/ {
      proxy_pass https://conduit-api.bondaracademy.com/api/;
      proxy_ssl_server_name on;
      proxy_set_header Host conduit-api.bondaracademy.com;
      proxy_set_header Origin "";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      try_files $uri /index.html;
    }
  }
}
